name: Deepwalk hetero embedding
description: Task to create embedding using deep walk on hetero graph
bind_mounts:
  - container_path: /root/data/ikg_v2_data
    host_path: /home/sachin/Projects/ikg_v2_data
    propagation: ''
    read_only: true
data:
    fold_n: "0"
hyperparameters:
    global_batch_size: 128
    embedding_dim: 128
    learning_rate: 0.00076
    walk_length: 44
    walks_per_node: 6
    p: 1
    q: 1
    context_size: 10
    num_negatives: 5
    restart: false
    early_stopping_delta: 0.01
    early_stopping_patience: 10
records_per_epoch: 231827
searcher:
    name: single
    metric: roc_score_link_pred
    smaller_is_better: false
    max_length:
        epochs: 500
min_validation_period:
    epochs: 1
checkpoint_policy: none
resources:
    slots_per_trial: 1
entrypoint: src.model.hetero_embedding.deep_walk_embedder:DeepWalkEmbedder
max_restarts: 0
environment:
  image: "sachinx0e/ikg:4.3"