name: EdgePredTest
description: Task to verify if edge prediction as an objective in HP search works
bind_mounts:
  - container_path: /root/data/ikg_v2_data
    host_path: /home/sachin/Projects/ikg_v2_data
    propagation: ''
    read_only: true
data:
    fold_n: "0"
hyperparameters:
    global_batch_size: 128
    embedding_dim:
        type: categorical
        vals: [64,80,96,128,256]
    learning_rate:
        type: double
        minval: 0.0001
        maxval: 0.001
    walk_length:
        type: int
        minval: 20
        maxval: 80
    walks_per_node:
        type: int
        minval: 5
        maxval: 10
    context_size:
        type: categorical
        vals: [6,8,10,12,16]
    num_negatives:
        type: int
        minval: 2
        maxval: 8
    p: 1
    q: 1
    early_stopping_delta: 0.001
    early_stopping_patience: 10
records_per_epoch: 2426
searcher:
    name: adaptive_asha
    metric: roc_score
    smaller_is_better: false
    max_length:
        epochs: 50
    max_trials: 50
min_validation_period:
    epochs: 1
checkpoint_policy: none
resources:
    slots_per_trial: 1
entrypoint: src.model.hetero_embedding.edge_pred_test:EdgePredTest
max_restarts: 0
environment:
  image: "sachinx0e/ikg:4.3"