name: TransE embedding - HP tune
description: Task to create embedding using TransE on hetero graph
bind_mounts:
  - container_path: /root/data/ikg_v2_data
    host_path: /home/sachin/Projects/ikg_v2_data
    propagation: ''
    read_only: true
data:
    fold_n: "0"
hyperparameters:
    global_batch_size: 256
    learning_rate:
        type: double
        minval: 0.0001
        maxval: 0.001
    embedding_dim:
        type: categorical
        vals: [64,80,96,128,256,320]
    num_negatives: 
        type: int
        minval: 2
        maxval: 8
    early_stopping_delta: 0.1
    early_stopping_patience: 5
    sets: "0,20"
records_per_epoch: 777267
searcher:
    name: adaptive_asha
    metric: roc_link_pred
    smaller_is_better: false
    max_length:
        epochs: 50
    max_trials: 50
min_validation_period:
    epochs: 1
checkpoint_policy: none
resources:
    slots_per_trial: 1
    resource_pool: tesla_pool
entrypoint: src.model.hetero_embedding.trans_e_embedder:TransEmbedder
max_restarts: 0
environment:
  image: "sachinx0e/ikg:4.3"