name: TransE embedding (MUL SEEDS)
description: Task to create embedding using TransE on hetero graph using multiple seeds
bind_mounts:
  - container_path: /root/data/ikg_v2_data
    host_path: /home/sachin/Projects/ikg_v2_data
    propagation: ''
    read_only: true
hyperparameters:
    global_batch_size: 64
    learning_rate: 0.0006
    embedding_dim: 64
    num_negatives: 6
    early_stopping_delta: 0.1
    early_stopping_patience: 5
    sets:
        type: categorical
        vals: ["0,20","1,22","2,24","3,26","4,28","5,30","6,32","7,34","8,36","9,38"]
records_per_epoch: 777267
searcher:
    name: grid
    metric: val_loss
    smaller_is_better: true
    max_length:
        epochs: 70
min_validation_period:
    epochs: 1
checkpoint_policy: none
resources:
    slots_per_trial: 1
    resource_pool: rtx_pool
entrypoint: src.model.hetero_embedding.trans_e_embedder:TransEmbedder
max_restarts: 0
environment:
  image: "sachinx0e/ikg:4.3"