name: Triples walk hetero embedding task - CB
description: Task to create embeddings using triple walk on hetero graph using CBOW
bind_mounts:
  - container_path: /root/data/ikg_v2_data
    host_path: /home/sachin/Projects/ikg_v2_data
    propagation: ''
    read_only: true
data:
    fold_n: "0"
    sample_targets: false
hyperparameters:
    global_batch_size: 128
    embedding_dim: 128
    learning_rate: 0.0007
    walk_length: 13
    walks_per_node: 8
    context_size: 12
    num_negatives: 7
    edge_op: hd
    early_stopping_delta: 0.1
    early_stopping_patience: 10
records_per_epoch: 231827
searcher:
    name: single
    metric: roc_score_link_pred
    smaller_is_better: false
    max_length:
        epochs: 500
min_validation_period:
    epochs: 1
checkpoint_policy: none
resources:
    slots_per_trial: 1
entrypoint: src.model.hetero_embedding.triple_walk_embedder_cbow:TripleWalkEmbedderCbow
max_restarts: 0
environment:
  image: "sachinx0e/ikg:4.7"