name: Cora trial
description: Test if the inhouse node2vec algorithm can train on the cora dataset
bind_mounts:
  - container_path: /root/data/ikg_v2_data
    host_path: /home/sachin/Projects/ikg_v2_data
    propagation: ''
    read_only: true
hyperparameters:
    global_batch_size: 96
    learning_rate: 0.0001
    embedding_dim: 128
    walk_length: 50
    walks_per_node: 10
    p: 0.4
    q: 0.8
    context_size: 5
    num_negatives: 10
    early_stopping_patience: 10
    early_stopping_delta: 0.0001
records_per_epoch: 2437
searcher:
    name: single
    metric: roc_score
    smaller_is_better: false
    max_length:
        epochs: 2000
min_validation_period:
        epochs: 1
checkpoint_policy: none
resources:
    slots_per_trial: 1
entrypoint: src.model_tests.cora_embedder:CoraEmbedderTrial
max_restarts: 0
environment:
  image: "sachinx0e/ikg:4.7"