name: GO embedder BP trial
description: Trial to determine the best hyper-params for GO BP embedding
bind_mounts:
  - container_path: /root/data/ikg_v2_data
    host_path: /home/sachin/Projects/ikg_v2_data
    propagation: ''
    read_only: true
data:
    go_type: "bp"
hyperparameters:
    global_batch_size: 128
    embedding_dim:
        type: categorical
        vals: [64,80,96,128,256]
    learning_rate:
        type: double
        minval: 0.0001
        maxval: 0.001
    walk_length:
        type: int
        minval: 60
        maxval: 140
    walks_per_node:
        type: int
        minval: 5
        maxval: 10
    p:
        type: double
        minval: 0.1
        maxval: 1.0
    q:
        type: double
        minval: 0.1
        maxval: 1.0
    context_size:
        type: categorical
        vals: [6,8,10,12,16,20]
    num_negatives:
        type: int
        minval: 2
        maxval: 6
records_per_epoch: 25678
searcher:
    name: adaptive_asha
    metric: clf_acc
    smaller_is_better: false
    max_length:
        epochs: 150
    max_trials: 50
min_validation_period:
    batches: 2000
checkpoint_policy: none
resources:
    slots_per_trial: 1
entrypoint: src.model.go_embedder:GoEmbedder
max_restarts: 0
environment:
  image: "sachinx0e/ikg:3.2"