name: Prediction task
description: Task to predict PPI using embeddings
bind_mounts:
  - container_path: /root/data/ikg_v2_data
    host_path: /home/sachin/Projects/ikg_v2_data
    propagation: ''
    read_only: true
hyperparameters:
    fold_n: "0"
    sampler_type: "random_sampler"
    learning_rate: 0.01
    global_batch_size: 64
    early_stopping_delta: 0.001
    early_stopping_patience: 10
records_per_epoch: 12134
searcher:
    name: single
    metric: val_loss
    smaller_is_better: true
    max_length:
        epochs: 100
min_validation_period:
    epochs: 1
checkpoint_policy: none
resources:
    slots_per_trial: 1
entrypoint: src.experiment.predict_model_trial:PredictionModelTrial
max_restarts: 0
environment:
  image: "sachinx0e/ikg:3.3"